server {
	server_name localhost1
	host 127.0.0.1
	port 8080
	client_max_body 1000000
	error_page 404 ./pages/Alps/error/404.html
	error_page 400 ./pages/Alps/error/400.html
	error_page 403 ./pages/Alps/error/403.html
	error_page 500 ./pages/Alps/error/500.html
	error_page 503 ./pages/Alps/error/503.html

	route / {
		route_name /
		allowed_methods GET

		root /pages/Alps/
		index index.html
		upload_status 0
		autoindex 0
	}

	route /cgi-bin {
		route_name /cgi-bin
		allowed_methods GET POST

		root /pages/Alps/cgi-bin
		index cgi.php
		upload_status 0
		autoindex 0

		cgi_path /usr/bin/php-cgi
		cgi_ext .php
	}

	route /upload {
		route_name /upload
		allowed_methods GET POST DELETE

		root /pages/Alps/upload/
		index upload.php
		upload_status 1
		autoindex 1

		cgi_path /usr/bin/php-cgi
		cgi_ext .php
	}
}

# server {
# 	server_name localhost2
# 	host 127.0.0.1
# 	port 9000
# 	client_max_body 1000000
# 	error_page 404 ./pages/Alps/error/404.html
# 	error_page 400 ./pages/Alps/error/400.html
# 	error_page 403 ./pages/Alps/error/403.html
# 	error_page 500 ./pages/Alps/error/500.html
# 	error_page 503 ./pages/Alps/error/503.html

# 	route / {
# 		route_name /
# 		allowed_methods GET

# 		root /pages/Alps/
# 		index index.html
# 		upload_status 0
# 		autoindex 0
# 	}

# 	route /cgi-bin {
# 		route_name /cgi-bin
# 		allowed_methods GET POST

# 		root /pages/Alps/cgi-bin
# 		index cgi.php
# 		upload_status 0
# 		autoindex 0

# 		cgi_path /usr/bin/php-cgi
# 		cgi_ext .php
# 	}

# 	route /upload {
# 		route_name /upload
# 		allowed_methods GET POST DELETE

# 		root /pages/Alps/upload/
# 		index upload.php
# 		upload_status 1
# 		autoindex 1
# 		# redirection 307 URI

# 		cgi_path /usr/bin/php-cgi
# 		cgi_ext .php
# 	}
# }