server {
	server_name localhost1
	host 127.0.0.1
	port 8080
	client_max_body 1000000
	error_page 404 /pages/error/404.html
# 	error_page 401 /pages/error/401.html
#	error_page 402 /pages/error/402.html
#	error_page 403 /pages/error/403.html
	route / {
		route_name /
		allowed_methods GET

		root /home/ttas/Webserv/pages/Alps/
		index /home/ttas/Webserv/pages/Alps/index.html
		upload 0
		autoindex 0

		cgi_path /home/ttas/Webserv/pages/Alps/cgi-bin/
		cgi_ext .php
	}

# To do	
	route /upload {
		route_name /upload
		allowed_methods GET POST DELETE

		root /home/ttas/Webserv/pages/Alps/upload/
		index /home/ttas/Webserv/pages/Alps/upload/upload.php
		upload_directory /home/ttas/Webserv/pages/Alps/upload/
		# redirection 307 URI
		upload 1
		autoindex 1

		cgi_path /home/ttas/Webserv/pages/Alps/cgi-bin/
		cgi_ext .php
	}
}

# server {
# 	name localhost2
# 	host 127.0.0.1
# 	port 8080
# 	client_max_body 1000000

# 	error_page 404 /pages/error/404.html
# # 	error_page 401 /pages/error/401.html
# # 	error_page 402 /pages/error/402.html
# # 	error_page 403 /pages/error/403.html
# #
# # 	route / {
# # 		name /
# # 		allowed_methods GET POST DELETE

# # 		root /pages/
# # 		index /pages/index.html
# # 		upload 0
# # 		autoindex 0
# #
# # 		cgi_path /cgi-bin
# # 		cgi_ext .php .py
# # 	}
# #
# # 	route /error {
# # 		name /error
# # 		allowed_methods GET
# #
# # 		root /pages/error/
# # 		index /pages/error/404.html
# # 		upload 0
# # 		autoindex 0
# # 	}
# #
# # 	route /cgi-bin {
# # 		name /cgi-bin
# # 		allowed_methods GET POST
# #
# # 		root /cgi-bin
# # 		upload 0
# # 		autoindex 0
# #
# # 		cgi_path /cgi-bin
# # 		cgi_ext .php .py
# # 	}
# }